Repository daianeex/nttmatch, pull requests merged in 2022-06, with the labels that each got.

#3 feat: adicionando rotas iniciais do projeto
  package-lock.json
  package.json
  src/App.js
  src/Service/privateroute.js
Labels: good first issue

#4 feat: login settings firebase
  src/Pages/Login/authentication.js
  src/settings/firebaseAuth.js
  src/settings/firebaseSettings.js
Labels: feat

#6 Refactoring: settings firebase
  src/Pages/Login/authentication.js
  src/Service/firebaseAuth.js
  src/Service/firebaseSettings.js
Labels: refactoring

#7 Doc/organizacao
  src/App.js
  src/Routes/index.js
  src/Routes/privateroute.js
Labels: refactoring

#9 adiocionando padrão regex
  src/Components/input.jsx
  src/Pages/Register/index.jsx
Labels: feat

#10 Feat/add page login
  package-lock.json
  src/Components/button.jsx
  src/Components/input.jsx
  src/Components/radio.jsx
  src/Components/select.jsx
  src/Pages/Home/index.jsx
  src/Pages/Login/authentication.js
  src/Pages/Login/index.jsx
  src/Routes/index.js
  src/Service/firebaseAuth.js
  src/Service/firebaseSettings.js
  src/Service/token.js
Labels: feat

#11 login funcioando
  src/Components/button.jsx
  src/Components/input.jsx
  src/Pages/Login/authentication.js
  src/Pages/Login/index.jsx
  src/Routes/index.js
  src/Service/firebaseSettings.js
Labels: feat

#15 refactoring code register
  src/Pages/Register/index.jsx
Labels: refactoring

#20 Pegando os valores dos inputs e começando a lógica sem firebase
  src/Components/select.jsx
  src/Pages/Register/index.jsx
  src/Routes/index.js
  src/Routes/privateroute.js
  src/Service/api.js
Labels: feat

#23 Feat/get docs
  src/Components/select.jsx
  src/Pages/Feed/index.jsx
  src/Pages/Login/index.jsx
  src/Pages/Register/index.jsx
  src/Routes/privateroute.js
  src/Service/authentication.js
  src/Service/firebaseSettings.js
Labels: bug, documentation

#25 page previous
  src/Pages/Login/index.jsx
  src/Pages/Previous/index.css
  src/Pages/Previous/index.jsx
  src/Routes/index.js
  src/Service/authentication.js
Labels: feat

#26 Refactoring/css feed
  src/Pages/Feed/feed.css
  src/Pages/Feed/index.jsx
  src/Pages/Register/index.jsx
  src/Service/authentication.js
  src/Service/firebaseSettings.js
  src/index.css
Labels: refactoring

#27 Criando os Cards
  src/Components/card.jsx
  src/Pages/Feed/index.jsx
  src/Service/firebaseAuth.js
Labels: refactoring

#29 refatoracao register
  src/Components/buttonWhats.jsx
  src/Pages/Register/index.css
  src/Pages/Register/index.jsx
Labels: refactoring
